name: PvEManager
main: me.NoChance.PvEManager.PvEManager
version: 1.3.0
author: NoChance20
description: Allows Administrators To Avoid PvE Log.

permissions:
  pvemanager.nocombat:
    description: Exempts a player from being placed in combat
    default: op